### ISSUE TITLE
Unable to type into any of the fields with Firefox or Chrome for Windows (getting a constant refresh) when using Sandstorm

### ISSUE THREAD

**Issue by JonTheNiceGuy** [simonv3/IdeaOtter#1]
I host my Sandstorm instance behind an NginX reverse proxy, so I don't know if that is affecting things?

**Comment by simonv3** [comment]
@JonTheNiceGuy Interesting. I haven't tested on a self hosted Sandstorm instance at all. Is it a refresh loop (and then a crash?)? Can you see if the console logs (in the browser) print out any errors?

Or do you mean that it refreshes after typing into the fields?

I have experienced that the fields can't be edited when the instance is shared with someone other than the original owner. That's functionality I still have to work on.

**Comment by JonTheNiceGuy** [comment]
Feel free to try for yourself - https://sandstorm.sprig.gs

No crash, just a refresh and the logs just keep showing the user id.

As to the user experience, I can typically type 2 characters before a refresh event occurs.

**Comment by simonv3** [comment]
Looks like I need to be invited by an admin to test it out on there. I'll be in IRC #sandstorm on freenode for the next few hours to troubleshoot if you like.

**Comment by simonv3** [comment]
Hey @JonTheNiceGuy @paulproteus just pointed out that nginx might have weird issues with websockets. Since this is a meteor app it uses websockets quite a bit - do you have any luck with other meteor apps on the store? Rocket.Chat and Wekan are two apps that come to mind.

**Comment by paulproteus** [comment]
For a sample known-working nginx config, check out line 15 here:

https://github.com/sandstorm-io/sandstorm/blob/master/nginx-example.conf#L15

For what it's worth.

**Comment by simonv3** [comment]
I'm going to mark this as closed, as I don't think it's an IdeaOtter issue. Let me know if that's wrong.
