### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by sciunto** [simonv3/IdeaOtter#7]
Can we have a short guide to install this application on a server please?

Many thanks.

**Comment by simonv3** [comment]
Hey @sciunto!

Idea Otter is meant to be run on Sandstorm, you can install it from their appstore: https://apps.sandstorm.io/app/du1nkmp0edheyjq07rm8s1tzr4qs4ut7k24vc2ps0vzm30zp77y0

If you want instructions on how to get Sandstorm running on your server: https://docs.sandstorm.io/en/latest/administering/

**Comment by simonv3** [comment]
Alternatively, if you just want to run it as your own instance, it's a Meteor app - install [Meteor](http://docs.meteor.com/) and run meteor in the directory. A word of warning here though: IdeaOtter runs all of of its admin by Sandstorm, so you probably wouldn't have any real level of privacy in running it.

**Comment by sciunto** [comment]
yes, this is how I found this code :) Actually, I would like to install it without using sandstorm. i guess it should be possible

**Comment by sciunto** [comment]
ok

**Comment by simonv3** [comment]
I'm adding some more instructions to the readme.md right now :)

**Comment by simonv3** [comment]
Let me know if you get it up and running, and if you make changes, I'd love to review them for a PR!

**Comment by sciunto** [comment]
Thanks! I'll look at that.
